development:
  bucket: intlman-dev
  access_key_id: AKIAIYCIDADPFHX4LBAQ
  secret_access_key: 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

test:
  bucket: bucket-test
  access_key_id: AKIAIYCIDADPFHX4LBAQ
  secret_access_key: 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

production:
  bucket: intlman-production 
  access_key_id: AKIAIG4GALZA6OY3ZJNQ
  secret_access_key: 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