development:
  bucket: intlman 
  access_key_id: AKIAIYCIDADPFHX4LBAQ
  secret_access_key: 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

test:
  bucket: bucket-test
  access_key_id: xxx
  secret_access_key: xxx

production:
  bucket: intlman-prod
  access_key_id: AKIAIYCIDADPFHX4LBAQ
  secret_access_key: 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