development:
  bucket: intlman-dev
  access_key_id:
  secret_access_key:

test:
  bucket: bucket-test
  access_key_id:
  secret_access_key:

production:
  bucket: intlman-production 
  access_key_id:
  secret_access_key: